### ISSUE TITLE
Cannot extract mod folders into program

### ISSUE THREAD

**Issue by jordiboi123** [rootCBR/ManageLegion#3]
whenever i click and drag the mod folders into the left panel nothing happens but i can drag it into the right. also when i run the program as administrator it gives me a cross-out symbol so i cannot drag files there at all in administrator mode. any help would be appreciated!

**Comment by donutnotnut** [comment]
same here, couldnt do anything with it yet, could anyone help us?

**Comment by rootCBR** [comment]
Are the files compatible with ManageLegion? More specifically, are they zip archives that contain an `info.xml` file alongside the mod data?

I just released v1.03 which supports zip archives with their extension changed to `.mlp` to make mod packages easier to distinguish from normal zip files.

**Comment by jordiboi123** [comment]
okay i just realized that im an idiot.. the instructions are to drag the entire zip folder into the program and to NOT try to extract the folders into it. so @donutnotnut when you download a mod just drag the winrar file (or 7zip etc..) directly to the left pane and dont open it to move the files. hopefully you get it all figured out!... also sorry @rootCBR for wasting your time and i appreciate you getting back to me! Cheers!

**Comment by donutnotnut** [comment]
Yea, i did just move zip, program just doesnt do anything. Mods have info.xml too, they are compatible with managelegion,and basically say it on their webiste

**Comment by rootCBR** [comment]
Could you post the links to the files you're trying to load?

**Comment by donutnotnut** [comment]
> Could you post the links to the files you're trying to load?

Sure, here you go:
https://www.nexusmods.com/watchdogslegion/mods/16
https://www.nexusmods.com/watchdogslegion/mods/12

**Comment by donutnotnut** [comment]
OMFG o i found a solution, since windows sets all folders to read only and you cant change it, all you have to od is go to watch dogs folder>security, your user, and enable full acess, after doing it it fixed everything, you should add it to notes since Ive seen a lot of people trying to find an answer for this one
