### ISSUE TITLE
stuck on "deserializing patch archive"

### ISSUE THREAD

**Issue by Michauu31** [rootCBR/ManageLegion#7]
doesn't pack the mod, instead gets stuck on said phase

**Comment by enochjoue** [comment]
How donwload managelegion ?

**Comment by RequestResponder** [comment]
C:\Program Files\Epic Games\WatchDogsLegion\bin
Put it in the game executable square and it should go fine!

**Comment by Michauu31** [comment]
running as admin fixes issue
